#!/bin/sh

LOG_LEVEL=${ZAPPY_LOG_LEVEL:-INFO}
TEAM_NAMES=${ZAPPY_TEAM_NAMES:-"team1 team2"}
CLIENT_NUMBER=${ZAPPY_CLIENT_NUMBER:-4}
FREQUENCY=${ZAPPY_FREQUENCY:-100}
DISPLAYER="server/base.so"
PORT=4242
WIDTH=${ZAPPY_WIDTH:-10}
HEIGHT=${ZAPPY_HEIGHT:-10}

./zappy_server -p $PORT -x $WIDTH -y $HEIGHT -n $TEAM_NAMES -c $CLIENT_NUMBER -f $FREQUENCY -d $DISPLAYER -l $LOG_LEVEL --docker
