##
## EPITECH PROJECT, 2024
## Zappy
## File description:
## Makefile
##

all: server-tester

server-tester:
	$(MAKE) -C server-tester

clean:
	$(MAKE) clean -C server-tester

fclean:
	$(MAKE) fclean -C server-tester

re: fclean all

.PHONY: all clean fclean re server-tester
